### ISSUE TITLE
User Cluster Backup Document how to use

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#1707]
Currently a Minio S3 endpoint doesn't work out-of the box, see https://github.com/kubermatic/kubermatic/issues/13483. 

Right now it's possible to add additional parameters to the `config` for the [Backup Storage Location (for AWS)](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/backupstoragelocation.md) Object via the `ClusterBackupStorageLocation` object (at the seed). This should be documented.
 
```bash
export KUBECONFIG=path-to-seed-kubeconfig
kubectl apply -f clusterbackuplocation.project.x.yaml
```
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: ClusterBackupStorageLocation
metadata:
  labels:
    csbl-display-name: seed-minio
    project-id: YOUR-PROJECT-ID
  name: seed-minio-YOUR-PROJECT-ID
  namespace: kubermatic
spec:
  backupSyncPeriod: 1m0s
  config:
    region: minio
    ####  NOTE: URL must be accisble from the user cluster network scope
    s3Url: https://minio.demo.kubermatic.io 
    # Whether to use path-style addressing instead of virtual hosted bucket addressing. Set to "true"
    # if using a local storage service like MinIO.
    #
    # Optional (defaults to "false").
    s3ForcePathStyle: "true"
    # If specified, use this instead of "s3Url" when generating download URLs (e.g., for logs). This
    # field is primarily for local storage services like MinIO.
    #
  credential:
    key: cloud-credentials
    name: credential-seed-minio-nczgr7n44g-h6qkj    #located in kubermatic namespace
  objectStorage:
    bucket: user-cluster-backup
  provider: aws
```
