### ISSUE TITLE
User Cluster MLA documentation is missing `grafana.ini` configuration

### ISSUE THREAD

**Issue by embik** [kubermatic/docs#1877]
It seems that our User Cluster MLA admin instructions are missing crucial information on how to set up Grafana properly. The basic snippet that is missing is this:

```yaml
grafana:
  grafana.ini:
    server:
      domain: <domain>
      root_url: https://<domain>/
```

Without it, Grafana tries to redirect to localhost:3000 when e.g. changing orgs. Seems like something we should document somewhere.
